import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import Navbar from "@/components/navigation/navbar";
import ThemeProvider from "@/context/Theme";

const sansation = localFont({
  src: [
    {
      path: "./fonts/Sansation_Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Sansation_Bold_Italic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/Sansation_Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Sansation_Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Sansation_Light_Italic.ttf",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-sansation",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sansation.variable} bg-[#FFFFFF] antialiased dark:bg-[#000000]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
